### PR TITLE
Completed CSS-Three-Column-Layout

### PR DESCRIPTION
**Pull request by Henry-Nichols**
image

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Henry! The text under each option is not aligned with its neighbors, please fix this and I will take another look

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Yo dude! Please provide a screenshot fo your updated output to the pull request so I can take a look 😁

**Comment by Henry-Nichols** [comment]
image

**Comment by Henry-Nichols** [comment]
image

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
